name: Generate Pack Bindings

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Commit Hash
        id: commit_hash
        run: echo "COMMIT_HASH=1.0-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Resource pack generic binding generator
        uses: solid-resourcepack/binder-action@v1.0.1
        with:
          package: "club.mcsports.generated"
          artifact_id: "bindings"
          artifact_version: ${{ env.COMMIT_HASH }}
          namespaces: "generic"
          classname: 'GenericPackBindings'
      - name: Resource pack lobby binding generator
        uses: solid-resourcepack/binder-action@v1.0.1
        with:
          package: "club.mcsports.generated"
          artifact_id: "bindings"
          artifact_version: ${{ env.COMMIT_HASH }}
          namespaces: "lobby"
          classname: 'LobbyPackBindings'

      - name: Resource pack golf binding generator
        uses: solid-resourcepack/binder-action@v1.0.1
        with:
          package: "club.mcsports.generated"
          artifact_id: "bindings"
          artifact_version: ${{ env.COMMIT_HASH }}
          namespaces: "powergolf"
          classname: 'GolfPackBindings'
          should_publish: 'true'
          repo_user: 'deploy'
          repo_url: 'https://repo.mcsports.club/releases'
          repo_password: ${{ secrets.REPO_TOKEN }}

